export const cardData = [
    {
      heading: 'Anxiety',
      writer: 'Arni Sehgal',
      date: 'Nov 2024',
      catchy: "It was way tougher. Consistency and revision are the keys.",
      content: 'Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac sapien. Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac congue primis tortor porttitor et sapien.',
      cardBgColor: 'bg-[#CBCDFA]',
      sideBgColor: 'bg-[#F7F7A0]',
      articleText: 'Blogs',
    },
    {
      heading: 'Stress',
      writer: 'John Doe',
      date: 'Oct 2024',
      catchy: "It was way tougher. Consistency and revision are the keys.",
      content: 'Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac sapien. Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac congue primis tortor porttitor et sapien.',
      cardBgColor: 'bg-[#aae3d6]',
      sideBgColor: 'bg-[#F7F7A0]',
      articleText: 'Blogs',
    },
    {
      heading: 'Depression',
      writer: 'Jane Smith',
      date: 'Sep 2024',
      catchy: "It was way tougher. Consistency and revision are the keys.",
      content: 'Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac sapien. Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac congue primis tortor porttitor et sapien.',
      cardBgColor: 'bg-[#DFCFBE]',
      sideBgColor: 'bg-[#F7F7A0]',
      articleText: 'Blogs',
    },
    {
      heading: 'ADHD',
      writer: 'Alex Brown',
      date: 'Aug 2024',
      catchy: "It was way tougher. Consistency and revision are the keys.",
      content: 'Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac sapien. Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac congue primis tortor porttitor et sapien.',
      sideBgColor: 'bg-[#F7F7A0]',
      cardBgColor: 'bg-[#c9d19b]',
      articleText: 'Blogs',
    },
    // {
    //   heading: 'PTSD',
    //   writer: 'Chris White',
    //   date: 'Jul 2024',
    //   content: 'Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac sapien. Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac congue primis tortor porttitor et sapien.',
    //   cardBgColor: 'bg-[#9097FD]',
    //   sideBgColor: 'bg-[#F7F7A0]',
    //   articleText: 'Blogs',
    //   link: '#'
    // },
    // {
    //   heading: 'Teen Issues',
    //   writer: 'Arni Sehgal',
    //   date: 'Jun 2024',
    //   content: 'Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac sapien. Conubia ex senectus commodo; facilisis metus vel! Quam nec habitant vehicula tempor felis. Ac congue primis tortor porttitor et sapien.',
    //   cardBgColor: 'bg-[#deabcf]',
    //   sideBgColor: 'bg-[#F7F7A0]',
    //   articleText: 'Blogs',
    //   link: '#'
    // }
  ];